import type { LoadedElement } from "../cem-types";
import { componentName, kebabToCamel, slotPropName } from "../naming";
import { extractIdentifiers, renderAttrType } from "../render-types";

export interface RenderedFile {
  componentName: string;
  filename: string;
  classification: "passive" | "property-driven" | "selection-managed";
  contents: string;
}

export function renderPassive(el: LoadedElement): RenderedFile {
  const { pkg, tag, className, declaration: d } = el;
  const attrs = d.attributes ?? [];
  const slots = d.slots ?? [];
  const events = d.events ?? [];

  const attrCamelNames = new Set(attrs.map((a) => kebabToCamel(a.name)));
  const slotNames = slots.map((s) => slotPropName(s.name, attrCamelNames));

  const extraIdents = new Set<string>();
  for (const a of attrs) {
    for (const id of extractIdentifiers(a.type?.text)) extraIdents.add(id);
  }

  const propLines: string[] = [];
  for (const a of attrs) {
    const camel = kebabToCamel(a.name);
    const ty = renderAttrType(a.type?.text);
    if (a.description) propLines.push(`  /** ${a.description} */`);
    propLines.push(`  ${camel}?: ${ty};`);
  }
  for (let i = 0; i < slots.length; i++) {
    const s = slots[i]!;
    const name = slotNames[i]!;
    if (s.description) propLines.push(`  /** ${s.description} */`);
    propLines.push(`  ${name}?: Snippet;`);
  }
  for (const e of events) {
    const handler = `on${e.name}`;
    const ty = e.type?.text ?? "Event";
    if (e.description) propLines.push(`  /** ${e.description} */`);
    propLines.push(`  ${handler}?: (e: ${ty}) => void;`);
  }
  propLines.push(`  element?: ${className};`);

  const destruct = [
    ...attrs.map((a) => kebabToCamel(a.name)),
    ...slotNames,
    ...events.map((e) => `on${e.name}`),
    "element = $bindable()",
  ].join(", ");

  const elementAttrs: string[] = [];
  for (const a of attrs) {
    const camel = kebabToCamel(a.name);
    const ty = renderAttrType(a.type?.text);
    if (ty === "boolean") {
      elementAttrs.push(`${a.name}={${camel} || undefined}`);
    } else if (a.name === camel) {
      elementAttrs.push(`{${camel}}`);
    } else {
      elementAttrs.push(`${a.name}={${camel}}`);
    }
  }
  for (const e of events) elementAttrs.push(`on${e.name}={on${e.name}}`);

  const slotBody = slots
    .map((s, i) =>
      s.name === ""
        ? ""
        : `  {#if ${slotNames[i]}}<div slot="${s.name}" style="display:contents">{@render ${slotNames[i]}()}</div>{/if}`,
    )
    .filter(Boolean)
    .join("\n");
  const defaultSlot = slots.some((s) => s.name === "")
    ? "  {@render children?.()}"
    : "";

  const importLines: string[] = [
    `  import type { Snippet } from "svelte";`,
    `  import { browser } from "../runtime/env";`,
    `  if (browser) void import("${pkg}");`,
    `  import type { ${className} } from "${pkg}";`,
  ];
  if (extraIdents.size > 0) {
    importLines.push(
      `  import type { ${[...extraIdents].join(", ")} } from "${pkg}";`,
    );
  }

  const contents = `<!-- @generated by scripts/generate.ts — do not edit -->
<script lang="ts">
${importLines.join("\n")}

  interface Props {
${propLines.join("\n")}
  }

  let { ${destruct} }: Props = $props();
</script>

<${tag}
  bind:this={element}
  ${elementAttrs.join("\n  ")}
>
${[slotBody, defaultSlot].filter(Boolean).join("\n")}
</${tag}>
`;

  return {
    componentName: componentName(tag),
    filename: `${componentName(tag)}.svelte`,
    classification: "passive",
    contents,
  };
}
