import type { LoadedElement } from "./cem-types";
import { componentName } from "./naming";

export function renderIndex(elements: LoadedElement[]): string {
  const names = [...new Set(elements.map((e) => componentName(e.tag)))].sort();
  const lines = names.map(
    (name) => `export { default as ${name} } from "./generated/${name}.svelte";`,
  );
  return `// @generated by scripts/generate.ts — do not edit\nimport "./generated/styles.css";\n${lines.join("\n")}\n`;
}
