import type { LoadedElement } from "./cem-types";

// Overlay/transient elements whose unstyled pre-upgrade render flashes.
const FOUC_PATTERNS = [/dialog/, /menu/, /snackbar/, /tooltip/];

export function renderStyles(elements: LoadedElement[]): string {
  const tags = [...new Set(elements.map((e) => e.tag))]
    .filter((tag) => FOUC_PATTERNS.some((p) => p.test(tag)))
    .sort();
  const header = "/* @generated by scripts/generate.ts — do not edit */";
  if (tags.length === 0) return `${header}\n`;
  const selectors = tags.map((t) => `${t}:not(:defined)`).join(",\n");
  return `${header}\n${selectors} {\n  display: none !important;\n}\n`;
}
